# Site settings
title: PlayTempora
description: Website for my game about Temples and portals
baseurl: "/"
url: "http://PlayTempora.com"

# Author information
author:
  name: Extrenious
  email: JermainLewi@gmail.com

# Build settings
markdown: kramdown
theme: minima
remote_theme: "mmistakes/minimal-mistakes"
