name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Configure Git author identity
        run: |
          git config user.email "JermainLewi@gmail.com"
          git config user.name "Extrenious"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          TEMPORA_TOKEN: ${{ secrets.TEMPORA_TOKEN }}

      - name: Start backend server
        run: |
          npm install pm2 -g
          pm2 start server/app.js --name 'my-app'
        env:
          TEMPORA_TOKEN: ${{ secrets.TEMPORA_TOKEN }}
